const { pickFile, viewLogo, log } = require('./src/dialogs')
const removeAllCycles = require('./src/algorithm')
const loadGraph = require('./src/utils/loadGraph')

viewLogo()
pickFile()
  .then(dialogResult => loadGraph(dialogResult.pickedFile))
  .then(log('Original graph'))
  .then(removeAllCycles)
  .then(log('Reduced graph'))